---
abstract: 'XHTML format for Text::Diff::Unified'
author:
  - 'David E. Wheeler <david@justatheory.com>'
build_requires:
  Module::Build: 0.2701
  Test::More: 0.17
configure_requires:
  Module::Build: 0.2701
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Diff-HTML
provides:
  Text::Diff::HTML:
    file: lib/Text/Diff/HTML.pm
    version: 0.07
recommends:
  Test::Pod: 1.41
requires:
  HTML::Entities: 0
  Text::Diff: 0.11
resources:
  bugtracker: http://github.com/theory/text-diff-html/issues/
  homepage: http://search.cpan.org/dist/Text-Diff-HTML/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/theory/text-diff-html/
version: 0.07
